Search Feature for Component Props
mantinedev/mantine pull request #160
Opened 2021-07-16 10:39 UTC by ghana7989

Adding Search Feature for component props. Which completes the requirement as in here https://trello.com/c/obo7dTPn

2021-07-16 10:50 UTC, rtivital requested changes
Thanks for a new PR, please fix these changes so that it can be merged

2021-07-16 10:50 UTC, rtivital commented on docs/src/components/MdxPage/MdxPageTabs/MdxPageTabs.tsx
> +              <Input
Replace Input with TextInput, Input should only be used to build other inputs

2021-07-16 10:50 UTC, rtivital commented on docs/src/components/MdxPage/MdxPageTabs/MdxPageTabs.tsx
> +                onChange={(event: { currentTarget: { value: React.SetStateAction<string> } }) =>
When Input is replaced with TextInput onChange event type definition will not be required, remove it

2021-07-16 10:50 UTC, rtivital commented on docs/src/components/MdxPage/MdxPageTabs/PropsTable/PropsTable.tsx
> +      return <React.Fragment key={propKey} />;
Just return null

2021-07-16 10:50 UTC, rtivital commented on docs/src/components/MdxPage/MdxPageTabs/PropsTable/PropsTable.tsx
> +}) {
Put type in separate interface:

```tsx
interface PropsTableProps {
  component: string;
  searchValue: string;
}
```

2021-07-16 10:50 UTC, rtivital commented on docs/src/components/MdxPage/MdxPageTabs/PropsTable/PropsTable.tsx
> +  searchValue,
rename searchValue -> query

2021-07-16 10:50 UTC, rtivital commented on docs/src/components/MdxPage/MdxPageTabs/MdxPageTabs.tsx
> +                variant="default"
Remove variant, it sets dynamically based on color scheme

2021-07-16 10:59 UTC, ghana7989 reviewed
I fixed them

2021-07-16 12:17 UTC, ghana7989 commented
Is there anything else you want me to update?

2021-07-16 13:00 UTC, rtivital approved these changes

2021-07-17 12:21 UTC, merged

2021-07-17 12:21 UTC, rtivital commented
Thanks for PR, everything works good