Add paginateBy property for Range Calendar
mantinedev/mantine pull request #1806
Opened 2022-07-18 07:04 UTC by LarsBehrenberg

Hi, this is my suggestion for the Range calendar to specify how many months are scrolled at a time. Currently when clicking to next or previous months, the amount of months scrolled is decided by the amountOfMonths property. This update would allow the user to specify how many months are "scrolled" at a time. 

PS: Happy to discuss and thanks so much for the great project! 🙏

2022-07-23 10:36 UTC, rtivital requested changes
Please fix errors to merge this PR

2022-07-23 10:36 UTC, rtivital commented on src/mantine-dates/src/components/CalendarBase/CalendarBase.tsx
> +      paginateBy,
It should be `paginateBy = amountOfMonths` to assign default value

2022-07-23 10:55 UTC, rtivital commented
@LarsBehrenberg Please fix errors

2022-07-24 09:56 UTC, LarsBehrenberg commented
@rtivital fixed!

2022-07-24 18:03 UTC, merged

2022-07-24 18:03 UTC, rtivital commented
Thanks!