Fixes Issue 203
mantinedev/mantine pull request #219
Opened 2021-08-20 08:38 UTC by achmurali

This PR fixes Issue #203.

2021-08-20 09:01 UTC, rtivital requested changes

2021-08-20 09:01 UTC, rtivital commented on src/mantine-core/src/components/Select/Select.tsx
> +          onClick={() => dropdownOpened ? setDropdownOpened(false) : setDropdownOpened(true)}
`setDropdownOpened(o => !o)`

2021-08-20 09:01 UTC, rtivital commented on src/mantine-core/src/components/Select/Select.tsx
> +  useEffect(() => {
Remove logging

2021-08-22 18:31 UTC, rtivital commented
@achmurali thanks, it works great, can you also create a same behavior for MultiSelect component with separate PR?

2021-08-22 18:31 UTC, merged

2021-08-23 09:56 UTC, achmurali commented
> @achmurali thanks, it works great, can you also create a same behavior for MultiSelect component with separate PR?

Yeah, sure