[@mantine/hooks] Fixing `use-hash` extra rerendering issue
mantinedev/mantine pull request #3097
Opened 2022-12-02 01:46 UTC by hunterwilhelm

Two bugs fixed:
* If you `setHash` to something that doesn't start with "#" it would be reflect that temporarily in `hash`
* `setHashValue` was being called multiple times (one in the listener and the set hash) resulting in the multiple renders

Result:
* `setHash` only rerenders the page once.
* `hash` consistently starts with '#'

2022-12-02 07:32 UTC, rtivital requested changes

2022-12-02 07:32 UTC, rtivital commented on src/mantine-hooks/src/use-hash/use-hash.ts
> +  const [hash, setHashValue] = useState<string>(() => window.location.hash);
This will fail during ssr, window object does not exist.

2022-12-02 07:33 UTC, rtivital commented
Please fix failed tests

2022-12-02 18:41 UTC, rtivital commented
Please fix failed tests

2022-12-02 20:37 UTC, hunterwilhelm commented
Thanks! Sorry about that, I'm a little new to this.

2022-12-04 11:44 UTC, merged

2022-12-04 11:44 UTC, rtivital commented
Thanks!