[@mantine/form] use-form: add submitting and submitError + methods
mantinedev/mantine pull request #4020
Opened 2023-04-06 14:21 UTC by philipodev

as per #4011 

### use-form

* Added `submitting`, `submitError` fields
* Added `setSubmitting`, `setSubmitError` and `resetSubmitError` methods

2023-05-09 22:43 UTC, treemmett approved these changes
This looks great! Hopefully this gets implemented soon.

2023-05-09 23:05 UTC, treemmett requested changes

2023-05-09 23:05 UTC, treemmett commented on src/mantine-form/src/use-form.ts
> +  const [submitError, _setSubmitError] = useState<SubmitError>(null);
I think these should get reset in the [`reset` callback](https://github.com/mantinedev/mantine/pull/4020/files#diff-885f0cbfb62b24bda2ed7145a69597b51a67fabc68b78fde5b672962ed97559eR79)

2024-03-25 09:53 UTC, laugri commented
Hello, will this be implemented at some point ?

2024-04-29 07:22 UTC, ldalves commented
We are currently migrating a huge project from `React Hook Form` to `mantine/form` and we are very interested in this feature. Any estimates when this might be released?

2024-06-19 15:55 UTC, stevewillard commented
Any chance this could make it into the next release?

2024-06-22 10:40 UTC, closed without merging

2024-06-25 12:02 UTC, ldalves commented
why close? 😢  was created a separate PR and merged it or something like that?

2024-08-08 11:21 UTC, SergeyNedayvodaBit commented
hi, is this functionality still in the plans?

2024-09-05 21:42 UTC, geoguide commented
Weird silent close

2024-10-27 09:24 UTC, Akronae commented
I was really hoping for this feature just to show a loading spinner on my submit button 😭